name: fad
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_tts: ^3.2.3
  audioplayers: ^6.0.0
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.8
  clipboard: ^0.1.3
  speech_to_text: ^6.6.2
  flutter_statusbarcolor_ns: ^0.5.0
  google_fonts: ^6.2.1
  just_audio: ^0.9.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/images/loading_animation.gif"
    - "assets/images/menu.png"
    - "assets/images/changer.png"
    - "assets/images/france.png"
    - "assets/images/ci.png"
    - "assets/images/copie.png"
    - "assets/images/haut-parleur-audio.png"
    - "assets/images/record.png"
    - "assets/images/arretez.png"
    - "assets/images/partir.png"
    - "assets/images/star.png"
    - "assets/images/eclat.png"
    - "assets/images/warning.png"
    - "assets/images/plane.webp"
    - "assets/images/suggestion.png"
    - "assets/images/cross.png"
    - "assets/images/trash-can.png"
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
          weight: 600
